# Generated by Django 4.0 on 2022-05-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocurrencia',
            name='rango_mayor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocurrencia',
            name='rango_menor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
