# Generated by Django 4.0 on 2022-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0002_ocurrencia_rango_mayor_ocurrencia_rango_menor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidadcpr',
            name='fallas',
            field=models.PositiveIntegerField(blank=True, verbose_name='NÚMERO DE FALLAS'),
        ),
    ]
