# Generated by Django 4.0 on 2022-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_equipo_capacidad_alter_equipo_codigo_de_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='equipo_principal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Subsistema'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='planta_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Planta'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='planta_secundaria_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Planta Secundaria'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Sistema'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='subsistema_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Subsistema'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Tipo'),
        ),
        migrations.AddField(
            model_name='equipoprincipal',
            name='planta_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Planta Principal'),
        ),
        migrations.AddField(
            model_name='equipoprincipal',
            name='planta_secundaria_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Planta Secundaria'),
        ),
        migrations.AddField(
            model_name='equipoprincipal',
            name='sistema_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Sistema'),
        ),
        migrations.AddField(
            model_name='equipoprincipal',
            name='subsistema_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Subsistema'),
        ),
        migrations.AddField(
            model_name='equipoprincipal',
            name='tipo_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Tipo'),
        ),
    ]
