# Generated by Django 4.0 on 2022-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportConfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='clave',
            field=models.CharField(blank=True, max_length=70, verbose_name='Clave Maestra'),
        ),
    ]
