# Generated by Django 4.0 on 2022-05-13 21:33

from django.db import migrations, models
import reportConfig.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportConfig', '0004_alter_configuracionreporte_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[reportConfig.models.validate_image_extension], verbose_name='Logo de Empresa'),
        ),
    ]
